// Code generated by protoc-gen-go. DO NOT EDIT.
// source: service/pb/wikitable.proto

package pb

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	_ "github.com/grpc-ecosystem/grpc-gateway/protoc-gen-swagger/options"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Row struct {
	Columns              map[int64]string `protobuf:"bytes,1,rep,name=columns,proto3" json:"columns,omitempty" protobuf_key:"varint,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *Row) Reset()         { *m = Row{} }
func (m *Row) String() string { return proto.CompactTextString(m) }
func (*Row) ProtoMessage()    {}
func (*Row) Descriptor() ([]byte, []int) {
	return fileDescriptor_9ea30516c748ec90, []int{0}
}

func (m *Row) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Row.Unmarshal(m, b)
}
func (m *Row) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Row.Marshal(b, m, deterministic)
}
func (m *Row) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Row.Merge(m, src)
}
func (m *Row) XXX_Size() int {
	return xxx_messageInfo_Row.Size(m)
}
func (m *Row) XXX_DiscardUnknown() {
	xxx_messageInfo_Row.DiscardUnknown(m)
}

var xxx_messageInfo_Row proto.InternalMessageInfo

func (m *Row) GetColumns() map[int64]string {
	if m != nil {
		return m.Columns
	}
	return nil
}

type Table struct {
	Caption              string         `protobuf:"bytes,1,opt,name=caption,proto3" json:"caption,omitempty"`
	Rows                 map[int64]*Row `protobuf:"bytes,2,rep,name=rows,proto3" json:"rows,omitempty" protobuf_key:"varint,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *Table) Reset()         { *m = Table{} }
func (m *Table) String() string { return proto.CompactTextString(m) }
func (*Table) ProtoMessage()    {}
func (*Table) Descriptor() ([]byte, []int) {
	return fileDescriptor_9ea30516c748ec90, []int{1}
}

func (m *Table) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Table.Unmarshal(m, b)
}
func (m *Table) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Table.Marshal(b, m, deterministic)
}
func (m *Table) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Table.Merge(m, src)
}
func (m *Table) XXX_Size() int {
	return xxx_messageInfo_Table.Size(m)
}
func (m *Table) XXX_DiscardUnknown() {
	xxx_messageInfo_Table.DiscardUnknown(m)
}

var xxx_messageInfo_Table proto.InternalMessageInfo

func (m *Table) GetCaption() string {
	if m != nil {
		return m.Caption
	}
	return ""
}

func (m *Table) GetRows() map[int64]*Row {
	if m != nil {
		return m.Rows
	}
	return nil
}

type GetTablesRequest struct {
	Page                 string   `protobuf:"bytes,1,opt,name=page,proto3" json:"page,omitempty"`
	N                    []string `protobuf:"bytes,2,rep,name=n,proto3" json:"n,omitempty"`
	Lang                 string   `protobuf:"bytes,3,opt,name=lang,proto3" json:"lang,omitempty"`
	Table                []int32  `protobuf:"varint,4,rep,packed,name=table,proto3" json:"table,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetTablesRequest) Reset()         { *m = GetTablesRequest{} }
func (m *GetTablesRequest) String() string { return proto.CompactTextString(m) }
func (*GetTablesRequest) ProtoMessage()    {}
func (*GetTablesRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_9ea30516c748ec90, []int{2}
}

func (m *GetTablesRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetTablesRequest.Unmarshal(m, b)
}
func (m *GetTablesRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetTablesRequest.Marshal(b, m, deterministic)
}
func (m *GetTablesRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetTablesRequest.Merge(m, src)
}
func (m *GetTablesRequest) XXX_Size() int {
	return xxx_messageInfo_GetTablesRequest.Size(m)
}
func (m *GetTablesRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetTablesRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetTablesRequest proto.InternalMessageInfo

func (m *GetTablesRequest) GetPage() string {
	if m != nil {
		return m.Page
	}
	return ""
}

func (m *GetTablesRequest) GetN() []string {
	if m != nil {
		return m.N
	}
	return nil
}

func (m *GetTablesRequest) GetLang() string {
	if m != nil {
		return m.Lang
	}
	return ""
}

func (m *GetTablesRequest) GetTable() []int32 {
	if m != nil {
		return m.Table
	}
	return nil
}

type GetTablesResponse struct {
	Tables               []*Table `protobuf:"bytes,1,rep,name=tables,proto3" json:"tables,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetTablesResponse) Reset()         { *m = GetTablesResponse{} }
func (m *GetTablesResponse) String() string { return proto.CompactTextString(m) }
func (*GetTablesResponse) ProtoMessage()    {}
func (*GetTablesResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_9ea30516c748ec90, []int{3}
}

func (m *GetTablesResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetTablesResponse.Unmarshal(m, b)
}
func (m *GetTablesResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetTablesResponse.Marshal(b, m, deterministic)
}
func (m *GetTablesResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetTablesResponse.Merge(m, src)
}
func (m *GetTablesResponse) XXX_Size() int {
	return xxx_messageInfo_GetTablesResponse.Size(m)
}
func (m *GetTablesResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetTablesResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetTablesResponse proto.InternalMessageInfo

func (m *GetTablesResponse) GetTables() []*Table {
	if m != nil {
		return m.Tables
	}
	return nil
}

func init() {
	proto.RegisterType((*Row)(nil), "service.Row")
	proto.RegisterMapType((map[int64]string)(nil), "service.Row.ColumnsEntry")
	proto.RegisterType((*Table)(nil), "service.Table")
	proto.RegisterMapType((map[int64]*Row)(nil), "service.Table.RowsEntry")
	proto.RegisterType((*GetTablesRequest)(nil), "service.GetTablesRequest")
	proto.RegisterType((*GetTablesResponse)(nil), "service.GetTablesResponse")
}

func init() {
	proto.RegisterFile("service/pb/wikitable.proto", fileDescriptor_9ea30516c748ec90)
}

var fileDescriptor_9ea30516c748ec90 = []byte{
	// 454 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x53, 0xdd, 0x8a, 0xd3, 0x40,
	0x18, 0x65, 0x9a, 0x76, 0x4b, 0xbe, 0x56, 0xdd, 0x8e, 0x22, 0xb3, 0x41, 0x24, 0xe4, 0x42, 0xc2,
	0xb2, 0x4d, 0x30, 0x7b, 0x23, 0x2b, 0x0a, 0xab, 0x2c, 0xe2, 0x9d, 0x0c, 0xa2, 0xe0, 0x85, 0x32,
	0x09, 0x43, 0x0c, 0xcd, 0xce, 0xc4, 0xcc, 0xb4, 0xa1, 0x88, 0x37, 0x3e, 0x82, 0x82, 0xcf, 0x25,
	0xf8, 0x0a, 0x3e, 0x88, 0xcc, 0x24, 0x4d, 0xa3, 0xee, 0xd5, 0xde, 0xb4, 0xf3, 0xe5, 0x9c, 0xef,
	0x3b, 0xe7, 0xcc, 0x0f, 0x78, 0x8a, 0xd7, 0x9b, 0x22, 0xe3, 0x71, 0x95, 0xc6, 0x4d, 0xb1, 0x2a,
	0x34, 0x4b, 0x4b, 0x1e, 0x55, 0xb5, 0xd4, 0x12, 0x4f, 0x3b, 0xcc, 0xbb, 0x97, 0x4b, 0x99, 0x97,
	0x3c, 0x66, 0x55, 0x11, 0x33, 0x21, 0xa4, 0x66, 0xba, 0x90, 0x42, 0xb5, 0x34, 0xef, 0xc4, 0xfe,
	0x65, 0xcb, 0x9c, 0x8b, 0xa5, 0x6a, 0x58, 0x9e, 0xf3, 0x3a, 0x96, 0x95, 0x65, 0xfc, 0xcf, 0x0e,
	0x36, 0xe0, 0x50, 0xd9, 0xe0, 0x53, 0x98, 0x66, 0xb2, 0x5c, 0x5f, 0x0a, 0x45, 0x90, 0xef, 0x84,
	0xb3, 0xe4, 0x28, 0xea, 0xd4, 0x22, 0x2a, 0x9b, 0xe8, 0x79, 0x8b, 0x5d, 0x08, 0x5d, 0x6f, 0xe9,
	0x8e, 0xe9, 0x9d, 0xc1, 0x7c, 0x08, 0xe0, 0x43, 0x70, 0x56, 0x7c, 0x4b, 0x90, 0x8f, 0x42, 0x87,
	0x9a, 0x25, 0xbe, 0x03, 0x93, 0x0d, 0x2b, 0xd7, 0x9c, 0x8c, 0x7c, 0x14, 0xba, 0xb4, 0x2d, 0xce,
	0x46, 0x8f, 0x50, 0xf0, 0x03, 0xc1, 0xe4, 0xb5, 0x09, 0x87, 0x09, 0x4c, 0x33, 0x66, 0xfd, 0xd9,
	0x4e, 0x97, 0xee, 0x4a, 0x7c, 0x02, 0xe3, 0x5a, 0x36, 0x8a, 0x8c, 0xac, 0x23, 0xd2, 0x3b, 0xb2,
	0x7d, 0xc6, 0x57, 0x67, 0xc8, 0xb2, 0xbc, 0x0b, 0x70, 0xfb, 0x4f, 0x57, 0x58, 0x09, 0x86, 0x56,
	0x66, 0xc9, 0x7c, 0x98, 0x6f, 0x68, 0xec, 0x3d, 0x1c, 0xbe, 0xe0, 0xda, 0x4a, 0x28, 0xca, 0x3f,
	0xad, 0xb9, 0xd2, 0x18, 0xc3, 0xb8, 0x62, 0x39, 0xef, 0xfc, 0xd9, 0x35, 0x9e, 0x03, 0x12, 0xd6,
	0x99, 0x4b, 0x91, 0x30, 0x8c, 0x92, 0x89, 0x9c, 0x38, 0x2d, 0xc3, 0xac, 0x4d, 0x78, 0x7b, 0x7c,
	0x64, 0xec, 0x3b, 0xe1, 0x84, 0xb6, 0x45, 0xf0, 0x18, 0x16, 0x83, 0xf9, 0xaa, 0x92, 0x42, 0x71,
	0xfc, 0x00, 0x0e, 0x2c, 0xba, 0xdb, 0xfd, 0x9b, 0x7f, 0x67, 0xa5, 0x1d, 0x9a, 0xfc, 0x44, 0xe0,
	0xbe, 0x2d, 0x56, 0x45, 0xbb, 0x73, 0x29, 0xb8, 0xfd, 0x28, 0xbc, 0x3f, 0xb0, 0x7f, 0xed, 0x7b,
	0xde, 0x55, 0x50, 0xab, 0x1c, 0xdc, 0xff, 0xfa, 0xeb, 0xf7, 0xf7, 0x11, 0xc1, 0x77, 0xed, 0x6d,
	0xda, 0x3c, 0x8c, 0x4d, 0xb8, 0xf8, 0xb3, 0xf9, 0x7d, 0x72, 0x7c, 0xfc, 0x05, 0x7f, 0x80, 0x59,
	0xdf, 0xf4, 0x26, 0xb9, 0xae, 0xca, 0x91, 0x55, 0xb9, 0x8d, 0x17, 0xad, 0x4a, 0xb2, 0x17, 0x78,
	0xf6, 0xf4, 0xdb, 0xf9, 0x02, 0xdf, 0x82, 0x1b, 0x7d, 0x2c, 0xff, 0xfc, 0xd5, 0xcb, 0x77, 0x61,
	0x5e, 0xe8, 0x8f, 0xeb, 0x34, 0xca, 0xe4, 0x65, 0xcc, 0xf4, 0x96, 0xef, 0x1f, 0xc3, 0xd2, 0x4c,
	0xd8, 0xbf, 0x92, 0xf4, 0xc0, 0xde, 0xe3, 0xd3, 0x3f, 0x01, 0x00, 0x00, 0xff, 0xff, 0xb8, 0x58,
	0x74, 0xbe, 0x3a, 0x03, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// WikiTableClient is the client API for WikiTable service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type WikiTableClient interface {
	GetTables(ctx context.Context, in *GetTablesRequest, opts ...grpc.CallOption) (*GetTablesResponse, error)
	GetTablesV2(ctx context.Context, in *GetTablesRequest, opts ...grpc.CallOption) (*GetTablesResponse, error)
}

type wikiTableClient struct {
	cc grpc.ClientConnInterface
}

func NewWikiTableClient(cc grpc.ClientConnInterface) WikiTableClient {
	return &wikiTableClient{cc}
}

func (c *wikiTableClient) GetTables(ctx context.Context, in *GetTablesRequest, opts ...grpc.CallOption) (*GetTablesResponse, error) {
	out := new(GetTablesResponse)
	err := c.cc.Invoke(ctx, "/service.WikiTable/GetTables", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *wikiTableClient) GetTablesV2(ctx context.Context, in *GetTablesRequest, opts ...grpc.CallOption) (*GetTablesResponse, error) {
	out := new(GetTablesResponse)
	err := c.cc.Invoke(ctx, "/service.WikiTable/GetTablesV2", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// WikiTableServer is the server API for WikiTable service.
type WikiTableServer interface {
	GetTables(context.Context, *GetTablesRequest) (*GetTablesResponse, error)
	GetTablesV2(context.Context, *GetTablesRequest) (*GetTablesResponse, error)
}

// UnimplementedWikiTableServer can be embedded to have forward compatible implementations.
type UnimplementedWikiTableServer struct {
}

func (*UnimplementedWikiTableServer) GetTables(ctx context.Context, req *GetTablesRequest) (*GetTablesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetTables not implemented")
}
func (*UnimplementedWikiTableServer) GetTablesV2(ctx context.Context, req *GetTablesRequest) (*GetTablesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetTablesV2 not implemented")
}

func RegisterWikiTableServer(s *grpc.Server, srv WikiTableServer) {
	s.RegisterService(&_WikiTable_serviceDesc, srv)
}

func _WikiTable_GetTables_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetTablesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WikiTableServer).GetTables(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/service.WikiTable/GetTables",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WikiTableServer).GetTables(ctx, req.(*GetTablesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WikiTable_GetTablesV2_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetTablesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WikiTableServer).GetTablesV2(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/service.WikiTable/GetTablesV2",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WikiTableServer).GetTablesV2(ctx, req.(*GetTablesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _WikiTable_serviceDesc = grpc.ServiceDesc{
	ServiceName: "service.WikiTable",
	HandlerType: (*WikiTableServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetTables",
			Handler:    _WikiTable_GetTables_Handler,
		},
		{
			MethodName: "GetTablesV2",
			Handler:    _WikiTable_GetTablesV2_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "service/pb/wikitable.proto",
}
